[project]
name = "keylogger"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pynput>=1.8.1",
]

[tool.uv.workspace]
members = [
    "Music_Formatter",
]
